
function(automaticGameFolderOutput TARGET_NAME MOD_FOLDER wildlander_output steam_owrt_output steam_mods_output lorerim_mods_output lorerim3_mods_output)

    if(DEFINED ENV{WILDLANDER_OWRT_FOLDER} AND IS_DIRECTORY "$ENV{WILDLANDER_OWRT_FOLDER}" AND wildlander_output)
        copyOutputs("${TARGET_NAME}" "$ENV{WILDLANDER_OWRT_FOLDER}/${MOD_FOLDER}${PROJECT_SUFFIX}")
    endif()
    if(DEFINED ENV{SKYRIM_OWRT_FOLDER} AND IS_DIRECTORY "$ENV{SKYRIM_OWRT_FOLDER}" AND steam_owrt_output)
        copyOutputs("${TARGET_NAME}" "$ENV{SKYRIM_OWRT_FOLDER}/${MOD_FOLDER}${PROJECT_SUFFIX}")
    endif()
    if(DEFINED ENV{SKYRIM_MODS_FOLDER} AND IS_DIRECTORY "$ENV{SKYRIM_MODS_FOLDER}" AND steam_mods_output)
        copyOutputs("${TARGET_NAME}" "$ENV{SKYRIM_MODS_FOLDER}/${MOD_FOLDER}${PROJECT_SUFFIX}")
    endif()
    if(DEFINED ENV{SKYRIM_MODS_FOLDER2} AND IS_DIRECTORY "$ENV{SKYRIM_MODS_FOLDER2}" AND steam_mods_output)
        copyOutputs("${TARGET_NAME}" "$ENV{SKYRIM_MODS_FOLDER2}/${MOD_FOLDER}${PROJECT_SUFFIX}")
    endif()
    if(DEFINED ENV{LORERIM_MODS_FOLDER} AND IS_DIRECTORY "$ENV{LORERIM_MODS_FOLDER}" AND lorerim_mods_output)
        copyOutputs("${TARGET_NAME}" "$ENV{LORERIM_MODS_FOLDER}/${MOD_FOLDER}${PROJECT_SUFFIX}")
    endif()
    if(DEFINED ENV{LORERIM3_MODS_FOLDER} AND IS_DIRECTORY "$ENV{LORERIM3_MODS_FOLDER}" AND lorerim3_mods_output)
        copyOutputs("${TARGET_NAME}" "$ENV{LORERIM3_MODS_FOLDER}/${MOD_FOLDER}${PROJECT_SUFFIX}")
    endif()

endfunction()
